### ISSUE TITLE
IndexError: index -1 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by ding-Chen** [bowenc0221/panoptic-deeplab#111]
Hello, I made the following error during the test. Do you know the reason? Thank you very much for your reply
![1637914510(1)](https://user-images.githubusercontent.com/85236372/143548740-64d3d603-b1d7-4bd6-a126-0461587e8f81.jpg)

**Comment by ankur-chr** [comment]
How did you solve this?
