### ISSUE TITLE
[Discussion] Changing Instance Segmentation Head to 2D Detection Head

### ISSUE THREAD

**Issue by timothylimyl** [bowenc0221/panoptic-deeplab#112]
Hi there (@bowenc0221, @tingliu, @PkuRainBow , @YknZhu , @mcollinswisc),

Do you think that changing the instance segmentation head to a detection head like YOLO is feasible/a good idea?  Seems like the instance seg head and object detection head are very alike.  For my application, I do not really need panoptic segmentation but semantic segmentation + object detection will be more suitable.

I have read some panoptic methods actually does object detection first and then post-merge with semantic segmentation to form panoptic segmentation, did you perform any experiment in this area for your network design? I am very curious to know your thoughts on this to gain additional insight before I proceed to re-design the network.

**Comment by bowenc0221** [comment]
No, we have not tried to replace the instance center prediction head with an object detection head.
