### ISSUE TITLE
CUDA out of memory even on Google colab

### ISSUE THREAD

**Issue by ankur-chr** [bowenc0221/panoptic-deeplab#118]
Hi,

I am getting this out of memory issue, even on Google Colab. How can we solve it?

RuntimeError: CUDA out of memory. Tried to allocate 146.00 MiB (GPU 0; 14.76 GiB total capacity; 13.83 GiB already allocated; 15.75 MiB free; 13.97 GiB reserved in total by PyTorch)

**Comment by ankur-chr** [comment]
Changed the Images per batch to 1 which solved the issue.

TRAIN:
  IMS_PER_BATCH: 1

**Comment by fourmin** [comment]
Hi Ankur,

I also meet the problem. Where can change the parameter?
Thanks a lot!
