### ISSUE TITLE
[Contribution welcome] Reproduce Mapillary results

### ISSUE THREAD

**Issue by Hun-ger** [bowenc0221/panoptic-deeplab#12]
Thanks for the code. I see your method's score is very high in  Mapillary dataset provide by Paperswithcode. Is there pretrained model for Mapillary vistas dataset we can download?

**Comment by bowenc0221** [comment]
Unfortunately, there is no Mapillary Vistas pretrained model yet. Our original models are trained with TensorFlow and I haven't tried training models on Mapillary Vistas with this code yet.

**Comment by bowenc0221** [comment]
Mapillary Vistas panoptic segmentation has been supported in a recent work: https://github.com/facebookresearch/Mask2Former

Please refer to it if you are interested in Mapillary Vistas.

**Comment by innat-asj** [comment]
@bowenc0221 Is the original code available? If it's done with tf 1, I would like to translate it new tf 2 (keras) api.
