### ISSUE TITLE
how to visualize the result?

### ISSUE THREAD

**Issue by luohao123** [bowenc0221/panoptic-deeplab#14]
Any demo script provided inference on a single image and visualize the final result?

**Comment by bowenc0221** [comment]
Currently, there is no demo code yet, but there is a set of visualization codes that can visualize semantic, instance and panoptic segmentation; as well as all intermediate outputs (e.g. center, offset). Please check [save_annotation.py](https://github.com/bowenc0221/panoptic-deeplab/blob/master/segmentation/utils/save_annotation.py) and you can find the usage in https://github.com/bowenc0221/panoptic-deeplab/blob/7886c9fcbee9367a1961f62e7e4dd79db49bdf27/tools/test_net_single_core.py#L343-L370

You are welcome to submit a pull request if you can help to put these code together for a demo code on a single image.

**Comment by jinfagang** [comment]
how's the inference speed compares with other panopatic methods?

**Comment by bowenc0221** [comment]
> how's the inference speed compares with other panopatic methods?

Please check our [tech report](https://github.com/bowenc0221/panoptic-deeplab/blob/master/docs/tech_report.pdf) for detailed speed. Current post-processing is not optimized, our TensorFlow implementation could achieve 2~3ms per 1025x2049 image, which is much faster than other methods

**Comment by jinfagang** [comment]
2-3 ms for model forward or postprocessing? that's crazy if model forward time.

**Comment by jinfagang** [comment]
![image](https://user-images.githubusercontent.com/21303438/86213177-e2f91d80-bbab-11ea-9557-c38e4a78a08c.png)

why there is 100ms vs 2ms gap between postprocess?

**Comment by bowenc0221** [comment]
As mentioned in the report, post-processing is done in parallel in the original TensorFlow implementation. This PyTorch implementation does not optimize post-processing yet (so it is still using a for-loop).

**Comment by bowenc0221** [comment]
@luohao123 Please see #22 for a simple demo code to visualize results
