### ISSUE TITLE
R101 pretrained model load failed.

### ISSUE THREAD

**Issue by ruxiaobao** [bowenc0221/panoptic-deeplab#19]
Hi Bowen, 

Thanks for the great work.
I tried to use torch.load to read "panoptic_deeplab_R101_os32_cityscapes.pth".
And it has complaint that
`  File "/home/ruxiaobao/Project/miniconda2/envs/venv_panoptic_deeplab/lib/python3.6/site-packages/torch/serialization.py", line 780, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 735892 more bytes. The file might be corrupted.
`

**Comment by bowenc0221** [comment]
Could you check the size of the checkpoint? It should be ~285M. If you find the size smaller, then you probably need to download the checkpoint again.

**Comment by ruxiaobao** [comment]
Thanks for the quick reply. The google drive shows it is 276M. My local file is also 276M. Is there any chance the file in google drive got corrupted?

**Comment by bowenc0221** [comment]
I tried to upload it again, could you check if it is still corrupted (the same link)?
Google drive probably did some compression, it is 276M again on Google drive.
BTW, does the weight for X101 have the same problem?

**Comment by bowenc0221** [comment]
Hi @ruxiaobao 
I found the checkpoint was corrupted, I just uploaded the new checkpoints (for both R101 and X101). Please download them again using the same link. Thanks for raising this problem!

**Comment by ruxiaobao** [comment]
Works now, thanks a lot!
