### ISSUE TITLE
Head is simplified

### ISSUE THREAD

**Issue by LetsGoFir** [bowenc0221/panoptic-deeplab#2]
Thanks for your great work!
![image](https://user-images.githubusercontent.com/59643844/84502784-8e206080-aceb-11ea-9422-1f5562f6a589.png)
It seems like the part in the red rectangle is omitted, would it hurt the performance?

![image](https://user-images.githubusercontent.com/59643844/84502934-d2136580-aceb-11ea-8535-c07011bf68a5.png)

**Comment by bowenc0221** [comment]
Each head is a nn.Sequential with two modules, the first module (e.g. `instance_head.classifier.center.0`) is my implementation of depthwise separable conv. Which is the part in the red rectangle.

I didn't notice the channel is 32 (here I use 128 channel). Maybe worth trying if using 32 channels is better.

**Comment by LetsGoFir** [comment]
> Each head is a nn.Sequential with two modules, the first module (e.g. `instance_head.classifier.center.0`) is my implementation of depthwise separable conv. Which is the part in the red rectangle.
> 
> I didn't notice the channel is 32 (here I use 128 channel). Maybe worth trying if using 32 channels is better.

Thanks for your prompt reply! Could you tell me how to evaluate the PQ of CityScapes in your code, please?

**Comment by bowenc0221** [comment]
You can use `tools/test_net_single_core.py`.
See [this](https://github.com/bowenc0221/panoptic-deeplab/blob/master/GETTING_STARTED.md#training--evaluation-in-command-line) for detail.

**Comment by LetsGoFir** [comment]
I get some problems when evaluate PQ, and I solved it by change the followed lines in 'evalution/panoptic.py'
```
self._gt_json_file = os.path.join(gt_dir, 'annotations', 'cityscapes_fine_val.json')
self._gt_folder = os.path.join(gt_dir, 'panoptic')
```

and comment the below lines

```
# if self._train_id_to_eval_id is not None:
#     pred_class = self._train_id_to_eval_id[pred_class]
```
and add 'leftImg8bit' after image_id in line 318 in'tools/test_'.

```
image_id = '_'.join(image_filename_list[i].split('_')[:3]) + '_leftImg8bit'

**Comment by bowenc0221** [comment]
What is the error message?

**Comment by bowenc0221** [comment]
FYI, I update the instance head with 32 channels (the same as the paper) in pr #3

**Comment by LetsGoFir** [comment]
Good job!

The original code is below
```
self._gt_json_file = os.path.join(gt_dir, 'gtFine', 'cityscapes_panoptic_{}.json'.format(split))
self._gt_folder = os.path.join(gt_dir, 'gtFine', 'cityscapes_panoptic_{}'.format(split))
```
But I have not any file or dir named 'cityscapes_panoptic_val', I added the '_traindId' after that and still go wrong. Therefore I edit it by myself.

**Comment by bowenc0221** [comment]
It is generated by `python cityscapesscripts/preparation/createPanopticImgs.py` without `--use-train-id`

**Comment by LetsGoFir** [comment]
Small typo, 'panoptic_deeplab.py'.
```
panoptic-deeplab/segmentation/model/meta_arch/panopitc_deeplab.py

**Comment by bowenc0221** [comment]
Good catch, thanks!

**Comment by LetsGoFir** [comment]
Maybe
https://github.com/bowenc0221/panoptic-deeplab/blob/9c25646101152d7ae16978faab4b35cf9c08d070/segmentation/model/post_processing/instance_post_processing.py#L49
should be
```
top_k_scores, _ = torch.topk(torch.flatten(ctr_hmp), top_k)

**Comment by bowenc0221** [comment]
You are right, it should be `ctr_hmp` instead of `ctr_all`. This won't affect Cityscapes result since there are less than 200 instances on Cityscapes. Might affect COCO performance.

**Comment by LetsGoFir** [comment]
Typo?
![image](https://user-images.githubusercontent.com/59643844/94355031-07816a80-00b3-11eb-8be0-0b0b6ac231c4.png)

**Comment by bowenc0221** [comment]
Fixed. Thank you!
