### ISSUE TITLE
Waiting for the inference demo! 

### ISSUE THREAD

**Issue by Muyun99** [bowenc0221/panoptic-deeplab#20]
i really love your idea, and i want to inference on my dataset like a video :). I want to know how long you will add the inference code for single img or single video

**Comment by bowenc0221** [comment]
@Muyun99 Are you interested in contributing to the demo code? I can write a single inference code for an image, would you like to extend it to a video or a list of images?

**Comment by Muyun99** [comment]
> @Muyun99 Are you interested in contributing to the demo code? I can write a single inference code for an image, would you like to extend it to a video or a list of images?

i think i can contribute with your help.

**Comment by bowenc0221** [comment]
Please see for a simple demo code #22

**Comment by Muyun99** [comment]
> Please see #22 for a simple demo code
> If you also want to visualize it for a video, you can first decode video and put each frame (HxWx3 numpy array) in the `input_list`. You can also collect outputs and save into a video.

Thanks for your demo code, i get some result with my videos. But can you offer me some code for fusing the inference result to a segmentation image?

I mean how to fuse the raw image and the panoptic result? I try to use cv2.addWeighted() but failed. I am not sure how to use the images generated to these folds(output_dir/panoptic, output_dir/instance and output_dir/semantic)

**Comment by bowenc0221** [comment]
You need to crop the image as well before fusing them: https://github.com/bowenc0221/panoptic-deeplab/blob/f36a2d063911370aa71400e0d8a678e992147d56/tools/demo.py#L278-L280

You can check `save_annotation`, `save_instance_annotation` and `save_panoptic_annotation` on how to apply colormap to labels.

**Comment by bowenc0221** [comment]
Hi @Muyun99 
Please try to pull the new code (#28) and run demo with an additional flag `--merge-image`. This will fuse raw image with panoptic result.
