### ISSUE TITLE
Multi-scale and flip test implementation

### ISSUE THREAD

**Issue by pingjun18-li** [bowenc0221/panoptic-deeplab#25]
I have done the trick of multi_scales and flip as input images to improve the PQ, flip can get about +0.5 PQ, however, when i use the multi_scales the PQ declined, I just reshape the input as the paper's scales and compute the mean of outputs ['semantic','center','offsets'] and resize offsets(*(-1)flip) ; is there who have finish this part, or interested to check that codes?
It confused me several days .

> firstly, i comment out the codes about "change ASPP"
    # Change ASPP image pooling
    #output_stride = 2 ** (5 - sum(config.MODEL.BACKBONE.DILATION))
    #train_crop_h, train_crop_w = config.TEST.CROP_SIZE
    #scale = 1. / output_stride
    #pool_h = int((float(train_crop_h) - 1.0) * scale + 1.0)
    #pool_w = int((float(train_crop_w) - 1.0) * scale + 1.0)
    #model.set_image_pooling((pool_h, pool_w))

> secondly, replace the part 

                image = data.pop('image')
                out_dict = model(image)

> by 

                ###multi_scales pingjun.li
                image1 = data['raw_image'][0].cpu().numpy()
                out_dict= muliti_scales_inference(model,image1,config.TEST.SCALE_LIST,config.TEST.FLIP_TEST)

> where **muliti_scales_inference** is define as :

    def flip_tensor(x, dim):
        """
        Flip Tensor along a dimension
        """
        dim = x.dim() + dim if dim < 0 else dim
        return x[tuple(slice(None, None) if i != dim
                       else torch.arange(x.size(i) - 1, -1, -1).long()
                       for i in range(x.dim()))]
    def upsample_predictions(pred, input_shape,scale):
        # Override upsample method to correctly handle `offset`
        result = OrderedDict()
        for key in pred.keys():
            out = F.interpolate(pred[key], size=input_shape, mode='bilinear', align_corners=True)
            if 'offset' in key:#The order of second dim is (offset_y, offset_x)
                out *= 1.0/scale
            result[key] = out
        return result

    def muliti_scales_inference(model,raw_image,scales,flip):
        ##transforms
        transforms = T.Compose(
            [   T.ToTensor(),
                T.Normalize(config.DATASET.MEAN,config.DATASET.STD)])
        if flip:
            flip_range = 2
        else:
            flip_range = 1
        h,w,_ = raw_image.shape
        org_h_pad = (h + 31) // 32 * 32 + 1
        org_w_pad = (w + 31) // 32 * 32 + 1

        sum_semantic_with_flip=0
        sum_center_with_flip=0
        sum_offset_with_flip=0
        for i in range(len(scales)):
            image=raw_image
            scale = scales[i]
            raw_h = int(h*scale)
            raw_w = int(w*scale)
            image = cv2.resize(image,(raw_w,raw_h),interpolation=cv2.INTER_NEAREST).astype(np.int32)
            # pad image####
            new_h = (raw_h + 31) // 32 * 32 + 1
            new_w = (raw_w + 31) // 32 * 32 + 1
            input_image = np.zeros((new_h, new_w, 3), dtype=np.uint8)
            input_image[:, :] = config.DATASET.MEAN

            input_image[:raw_h, :raw_w, :] = image

            image, _ = transforms(input_image, None)
            image = image.unsqueeze(0).to(device)
            
            for flip in range(flip_range):
                if flip:
                    image=flip_tensor(image,3)
                out_dict = model(image)
                for key in out_dict.keys(): #return to raw_input shape
                    out_dict[key]=out_dict[key][:,:,:raw_h,:raw_w]

                if raw_h !=org_h_pad or raw_w != org_w_pad:
                    out_dict=upsample_predictions(out_dict,(org_h_pad, org_w_pad),scale)

                semantic_pred=F.softmax(out_dict['semantic'],dim=1)

                center_pred=out_dict['center']
                offset_pred=out_dict['offset']
                if flip:
                    semantic_pred=flip_tensor(semantic_pred,3)
                    center_pred=flip_tensor(center_pred,3)
                    offset_pred=flip_tensor(offset_pred,3)
                    offset_pred[:,1,:,:]*=(-1)

                sum_semantic_with_flip+=semantic_pred
                sum_center_with_flip+=center_pred
                sum_offset_with_flip+=offset_pred
                #pdb.set_trace()

        semantic_mean = sum_semantic_with_flip / (flip_range * len(scales))
        center_mean = sum_center_with_flip / (flip_range * len(scales))
        offset_mean = sum_offset_with_flip / (flip_range * len(scales))
        #semantic_mean_pred = torch.argmax(semantic_mean, dim=1)

        out_dict['semantic']=semantic_mean
        out_dict['center']=center_mean
        out_dict['offset']=offset_mean
        return out_dict

_Originally posted by @Alchemist-18 in https://github.com/bowenc0221/panoptic-deeplab/issues/8#issuecomment-660750779_

**Comment by bowenc0221** [comment]
Here is my suggesting to debug:
Could you try only do multi-scale on each individual component? For example, you only update `semantic` and leave `center` and `offset` unchanged. And see if the performance of multi-scale testing is still worse?

The first problem I spotted is you processed the image in a different way.

They way we do multiscale testing in our paper follows the logic in DeepLab: https://github.com/tensorflow/models/blob/57c08a083c341c7215df57c01b29b1064f34ac88/research/deeplab/model.py#L101

Could you try directly process the image instead of processing the `raw_image`. For example, you can directly resize the 1025x2049 image to 513x1025.

**Comment by Alchemist-18** [comment]
Yes, I have done only update the semantic the baseline(no flip) I have get (scale=1.0), 54.9 | 79.4 | 67.7 | 20.3 | 75.7 and scales=[0.5,0.75,1.0,1.25], get 54.2 | 79.3 | 66.8 | 19.4/37.1 | 76.0, the miou +0.3 but PQ get -0.7,and when scales=[0.5,0.75,1.0,1.25,1.5,1.75,2], the results worse  'pq': 51.6, 'sq': 78.9, 'rq': 63.5 ,'AP': 17.7 and 'mIoU': 72.9 

by the way, it's seem that the image (image = data.pop('image')) is float type,however the operation of resize needs int, so I used the raw_image 
.

**Comment by bowenc0221** [comment]
You can use `F.interpolate` with `align_corners=True` for float image. Ah, you also used NearestNeighbor which should be bilinar instead.

Have you tried only do multiscale for semantic?

**Comment by pingjun18-li** [comment]
Ah, it works now.
according to what you said, i just change the operation  of 'NearestNeighbor' to 'bilinar' and use the flip and scales= [0.5,0.75,1.0,1.25,1.5,1.75,2], the results as follow:

> Name | Multi-scales | Flip | PQ | SQ | RQ | AP | mIoU

-- | -- | -- | -- | -- | -- | -- | --
HR48-bowen |   |   | 63.4 | 81.5 | 76.7 | 29.9 | 80.9
HR48-flip |   | √ | 63.4 | 81.6 | 76.7 | 31.9/55.7 | 81.3
HR48-multi-flip | √ | √ | 64.3 | 82.1 | 77.5 | 33.1/57.1 | 82.1
R-50-bowen |   |   | 59.8 | 80 | 73.5 | 26.9 | 78.6
R-50-seg-branch | (seg branch only) | √ | 61.3 | 80.6 | 74.9 | 26.9 | 80
R-50-flip |   | √ | 60.3 | 80.3 | 73.8 | 27.9 | 79
R-50-multi-flip | √ | √ | 62.3 | 80.8 | 75.9 | 28.9/53.6 | 80
MBNV2_bowen |   |   | 55.1 | 79.4 | 68 | 20.6 | 75.8
MBNV2-flip |   | √ | 55.5 | 79.7 | 68.2 | 20.9 | 76.2
MBNV2-flip-multi | √ | √ | 58.7 | 80.4 | 71.7 | 26.4/44.7 | 77.75

>

**Comment by bowenc0221** [comment]
Nice!
It seems reasonable to have larger models benefit less from multi-scale and flip test. From your HRNet results, I feel it is reasonable compared to Xception-71 results in my paper.

Do you want to submit a PR to merge this feature to the master?

**Comment by pingjun18-li** [comment]
Yea, It is my profound pleasure to contribute to the project, however, due to the limit of my computer, I cannot submit a PR ,but I can paste the codes and merge that by your help.

> for config file '*.yaml'  i add the configs:

TEST:
  EVAL_INSTANCE: True
  EVAL_PANOPTIC: True
  MULTI_SCALE: True
  SCALE_LIST: [0.5,0.75,1.0,1.25,1.5,1.75,2]
  FLIP_TEST: True

> and  the testing codes modified on yours:

# ------------------------------------------------------------------------------
# Testing code.
# Example command:
# python tools/test_net_single_core.py --cfg PATH_TO_CONFIG_FILE
# Written by Bowen Cheng (bcheng9@illinois.edu)
# ------------------------------------------------------------------------------

import argparse
import cv2
import os
import pprint
import logging
import time
import pdb
import numpy as np
import torch
import torch.nn.functional as F
import torch.backends.cudnn as cudnn
import torchvision.transforms as transforms
import segmentation.data.transforms.transforms as T

from collections import OrderedDict
import _init_paths
from fvcore.common.file_io import PathManager
from segmentation.config import config, update_config
from segmentation.utils.logger import setup_logger
from segmentation.model import build_segmentation_model_from_cfg
from segmentation.data import build_train_loader_from_cfg, build_test_loader_from_cfg
from segmentation.utils import save_debug_images
from segmentation.utils import AverageMeter
from segmentation.model.post_processing import get_semantic_segmentation, get_panoptic_segmentation
from segmentation.utils import save_annotation, save_instance_annotation, save_panoptic_annotation
from segmentation.evaluation import (
    SemanticEvaluator, CityscapesInstanceEvaluator, CityscapesPanopticEvaluator,
    COCOInstanceEvaluator, COCOPanopticEvaluator)
from segmentation.model.post_processing import get_cityscapes_instance_format

os.environ["CUDA_VISIBLE_DEVICES"] = "0,1,2"
mean_std = ([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])

def parse_args():
    parser = argparse.ArgumentParser(description='Test segmentation network with single process')

    parser.add_argument('--cfg',
                        help='experiment configure file name',
                        required=True,
                        type=str)
    parser.add_argument('opts',
                        help="Modify config options using the command-line",
                        default=None,
                        nargs=argparse.REMAINDER)

    args = parser.parse_args()
    update_config(config, args)

    return args

def img_resize(img,size):
    im_resize=transforms.Compose([transforms.resize(size),
            transforms.ToTensor(), 
            transforms.Normalize(*mean_std)])
    image = im_resize(img)
    image = image.unsqueeze(0)
    return image

def tensor2img(tensor):
    to_pil = transforms.ToPILImage()
    image = tensor.cpu().clone()
    image = image.squeeze(0)
    image = to_pil(image)
    return image
def flip_tensor(x, dim):
    """
    Flip Tensor along a dimension
    """
    dim = x.dim() + dim if dim < 0 else dim
    return x[tuple(slice(None, None) if i != dim
                   else torch.arange(x.size(i) - 1, -1, -1).long()
                   for i in range(x.dim()))]

def main():
    args = parse_args()

    logger = logging.getLogger('segmentation_test')
    if not logger.isEnabledFor(logging.INFO):  # setup_logger is not called
        setup_logger(output=config.OUTPUT_DIR, name='segmentation_test')

    logger.info(pprint.pformat(args))
    logger.info(config)

    # cudnn related setting
    cudnn.benchmark = config.CUDNN.BENCHMARK
    cudnn.deterministic = config.CUDNN.DETERMINISTIC
    cudnn.enabled = config.CUDNN.ENABLED
    gpus = list(config.TEST.GPUS)
    if len(gpus) > 1:
        raise ValueError('Test only supports single core.')
    device = torch.device('cuda:{}'.format(gpus[0]))

    # build model
    model = build_segmentation_model_from_cfg(config)

    # Change ASPP image pooling
    #output_stride = 2 ** (5 - sum(config.MODEL.BACKBONE.DILATION))
    #train_crop_h, train_crop_w = config.TEST.CROP_SIZE
    #scale = 1. / output_stride
    #pool_h = int((float(train_crop_h) - 1.0) * scale + 1.0)
    #pool_w = int((float(train_crop_w) - 1.0) * scale + 1.0)

    #model.set_image_pooling((pool_h, pool_w))

    logger.info("Model:\n{}".format(model))
    model = model.to(device)

    # build data_loader
    data_loader = build_test_loader_from_cfg(config)

    # load model
    if config.TEST.MODEL_FILE:
        model_state_file = config.TEST.MODEL_FILE
    else:
        model_state_file = os.path.join(config.OUTPUT_DIR, 'final_state.pth')

    if os.path.isfile(model_state_file):
        model_weights = torch.load(model_state_file)
        if 'state_dict' in model_weights.keys():
            model_weights = model_weights['state_dict']
            logger.info('Evaluating a intermediate checkpoint.')
        model.load_state_dict(model_weights, strict=True)
        logger.info('Test model loaded from {}'.format(model_state_file))
    else:
        if not config.DEBUG.DEBUG:
            raise ValueError('Cannot find test model.')

    data_time = AverageMeter()
    net_time = AverageMeter()
    post_time = AverageMeter()
    timing_warmup_iter = 10

    semantic_metric = SemanticEvaluator(
        num_classes=data_loader.dataset.num_classes,
        ignore_label=data_loader.dataset.ignore_label,
        output_dir=os.path.join(config.OUTPUT_DIR, config.TEST.SEMANTIC_FOLDER),
        train_id_to_eval_id=data_loader.dataset.train_id_to_eval_id()
    )

    instance_metric = None
    panoptic_metric = None

    if config.TEST.EVAL_INSTANCE:
        if 'cityscapes' in config.DATASET.DATASET:
            instance_metric = CityscapesInstanceEvaluator(
                output_dir=os.path.join(config.OUTPUT_DIR, config.TEST.INSTANCE_FOLDER),
                train_id_to_eval_id=data_loader.dataset.train_id_to_eval_id(),
                gt_dir=os.path.join(config.DATASET.ROOT, 'gtFine', config.DATASET.TEST_SPLIT)
            )
        elif 'coco' in config.DATASET.DATASET:
            instance_metric = COCOInstanceEvaluator(
                output_dir=os.path.join(config.OUTPUT_DIR, config.TEST.INSTANCE_FOLDER),
                train_id_to_eval_id=data_loader.dataset.train_id_to_eval_id(),
                gt_dir=os.path.join(config.DATASET.ROOT, 'annotations',
                                    'instances_{}.json'.format(config.DATASET.TEST_SPLIT))
            )
        else:
            raise ValueError('Undefined evaluator for dataset {}'.format(config.DATASET.DATASET))

    if config.TEST.EVAL_PANOPTIC:
        if 'cityscapes' in config.DATASET.DATASET:
            panoptic_metric = CityscapesPanopticEvaluator(
                output_dir=os.path.join(config.OUTPUT_DIR, config.TEST.PANOPTIC_FOLDER),
                train_id_to_eval_id=data_loader.dataset.train_id_to_eval_id(),
                label_divisor=data_loader.dataset.label_divisor,
                void_label=data_loader.dataset.label_divisor * data_loader.dataset.ignore_label,
                gt_dir=config.DATASET.ROOT,
                split=config.DATASET.TEST_SPLIT,
                num_classes=data_loader.dataset.num_classes
            )
        elif 'coco' in config.DATASET.DATASET:
            panoptic_metric = COCOPanopticEvaluator(
                output_dir=os.path.join(config.OUTPUT_DIR, config.TEST.PANOPTIC_FOLDER),
                train_id_to_eval_id=data_loader.dataset.train_id_to_eval_id(),
                label_divisor=data_loader.dataset.label_divisor,
                void_label=data_loader.dataset.label_divisor * data_loader.dataset.ignore_label,
                gt_dir=config.DATASET.ROOT,
                split=config.DATASET.TEST_SPLIT,
                num_classes=data_loader.dataset.num_classes
            )
        else:
            raise ValueError('Undefined evaluator for dataset {}'.format(config.DATASET.DATASET))

    foreground_metric = None
    if config.TEST.EVAL_FOREGROUND:
        foreground_metric = SemanticEvaluator(
            num_classes=2,
            ignore_label=data_loader.dataset.ignore_label,
            output_dir=os.path.join(config.OUTPUT_DIR, config.TEST.FOREGROUND_FOLDER)
        )

    image_filename_list = [
        os.path.splitext(os.path.basename(ann))[0] for ann in data_loader.dataset.ann_list]

    # Debug output.
    if config.TEST.DEBUG:
        debug_out_dir = os.path.join(config.OUTPUT_DIR, 'debug_test')
        PathManager.mkdirs(debug_out_dir)
    def flip_tensor(x, dim):
        """
        Flip Tensor along a dimension
        """
        dim = x.dim() + dim if dim < 0 else dim
        return x[tuple(slice(None, None) if i != dim
                       else torch.arange(x.size(i) - 1, -1, -1).long()
                       for i in range(x.dim()))]
    def upsample_predictions(pred, input_shape,scale):
        # Override upsample method to correctly handle `offset`
        result = OrderedDict()
        for key in pred.keys():
            out = F.interpolate(pred[key], size=input_shape, mode='bilinear', align_corners=True)
            if 'offset' in key:#The order of second dim is (offset_y, offset_x)
                out *= 1.0/scale
            result[key] = out
        return result

    def muliti_scales_inference(model,raw_image,scales,flip):
        ##transforms
        transforms = T.Compose(
            [   T.ToTensor(),
                T.Normalize(config.DATASET.MEAN,config.DATASET.STD)])
        if flip:
            flip_range = 2
        else:
            flip_range = 1
        h,w,_ = raw_image.shape
        org_h_pad = (h + 31) // 32 * 32 + 1
        org_w_pad = (w + 31) // 32 * 32 + 1

        sum_semantic_with_flip=0
        sum_center_with_flip=0
        sum_offset_with_flip=0
        for i in range(len(scales)):
            image=raw_image
            scale = scales[i]
            raw_h = int(h*scale)
            raw_w = int(w*scale)
            image = cv2.resize(image,(raw_w,raw_h),interpolation=cv2.INTER_LINEAR).astype(np.int32)
            # pad image####
            new_h = (raw_h + 31) // 32 * 32 + 1
            new_w = (raw_w + 31) // 32 * 32 + 1
            input_image = np.zeros((new_h, new_w, 3), dtype=np.uint8)
            input_image[:, :] = config.DATASET.MEAN

            input_image[:raw_h, :raw_w, :] = image

            image, _ = transforms(input_image, None)
            image = image.unsqueeze(0).to(device)
            
            for flip in range(flip_range):
                if flip:
                    image=flip_tensor(image,3)
                out_dict = model(image)
                for key in out_dict.keys(): #return to raw_input shape
                    out_dict[key]=out_dict[key][:,:,:raw_h,:raw_w]

                if raw_h !=org_h_pad or raw_w != org_w_pad:
                    out_dict=upsample_predictions(out_dict,(org_h_pad, org_w_pad),scale)

                semantic_pred=F.softmax(out_dict['semantic'],dim=1)

                center_pred=out_dict['center']
                offset_pred=out_dict['offset']
                if flip:
                    semantic_pred=flip_tensor(semantic_pred,3)
                    center_pred=flip_tensor(center_pred,3)
                    offset_pred=flip_tensor(offset_pred,3)
                    offset_pred[:,1,:,:]*=(-1)

                sum_semantic_with_flip+=semantic_pred
                sum_center_with_flip+=center_pred
                sum_offset_with_flip+=offset_pred

        semantic_mean = sum_semantic_with_flip / (flip_range * len(scales))
        center_mean = sum_center_with_flip / (flip_range * len(scales))
        offset_mean = sum_offset_with_flip / (flip_range * len(scales))
        #semantic_mean_pred = torch.argmax(semantic_mean, dim=1)

        out_dict['semantic']=semantic_mean
        out_dict['center']=center_mean
        out_dict['offset']=offset_mean
        return out_dict
    
    scales=config.TEST.SCALE_LIST
    print(scales,config.TEST.FLIP_TEST)
    # Train loop.
    try:
        model.eval()
        with torch.no_grad():
            for i, data in enumerate(data_loader):
                if i == timing_warmup_iter:
                    data_time.reset()
                    net_time.reset()
                    post_time.reset()
                
                # data
                #start_time = time.time()
                for key in data.keys():
                    try:
                        data[key] = data[key].to(device)
                    except:
                        pass

                image = data.pop('image')
                #out_dict = model(image)
                ###multi_scales add by pingjun
                raw_image = data['raw_image'][0].cpu().numpy()
                out_dict= muliti_scales_inference(model,raw_image,scales,config.TEST.FLIP_TEST)

                start_time = time.time()
                semantic_pred = get_semantic_segmentation(out_dict['semantic'])
                #pdb.set_trace()
                if 'foreground' in out_dict:
                    foreground_pred = get_semantic_segmentation(out_dict['foreground'])
                else:
                    foreground_pred = None

                # Oracle experiment
                if config.TEST.ORACLE_SEMANTIC:
                    # Use predicted semantic for foreground
                    foreground_pred = torch.zeros_like(semantic_pred)
                    for thing_class in data_loader.dataset.thing_list:
                        foreground_pred[semantic_pred == thing_class] = 1
                    # Use gt semantic
                    semantic_pred = data['semantic']
                    # Set it to a stuff label
                    stuff_label = 0
                    while stuff_label in data_loader.dataset.thing_list:
                        stuff_label += 1
                    semantic_pred[semantic_pred == data_loader.dataset.ignore_label] = stuff_label
                if config.TEST.ORACLE_FOREGROUND:
                    foreground_pred = data['foreground']
                if config.TEST.ORACLE_CENTER:
                    out_dict['center'] = data['center']
                if config.TEST.ORACLE_OFFSET:
                    out_dict['offset'] = data['offset']

                if config.TEST.EVAL_INSTANCE or config.TEST.EVAL_PANOPTIC:
                    panoptic_pred, center_pred = get_panoptic_segmentation(
                        semantic_pred,
                        out_dict['center'],
                        out_dict['offset'],
                        thing_list=data_loader.dataset.thing_list,
                        label_divisor=data_loader.dataset.label_divisor,
                        stuff_area=config.POST_PROCESSING.STUFF_AREA,
                        void_label=(
                                data_loader.dataset.label_divisor *
                                data_loader.dataset.ignore_label),
                        threshold=config.POST_PROCESSING.CENTER_THRESHOLD,
                        nms_kernel=config.POST_PROCESSING.NMS_KERNEL,
                        top_k=config.POST_PROCESSING.TOP_K_INSTANCE,
                        foreground_mask=foreground_pred)
                else:
                    panoptic_pred = None
                torch.cuda.synchronize(device)
                post_time.update(time.time() - start_time)
                logger.info('[{}/{}]\t'
                            'Data Time: {data_time.val:.3f}s ({data_time.avg:.3f}s)\t'
                            'Network Time: {net_time.val:.3f}s ({net_time.avg:.3f}s)\t'
                            'Post-processing Time: {post_time.val:.3f}s ({post_time.avg:.3f}s)\t'.format(
                             i, len(data_loader), data_time=data_time, net_time=net_time, post_time=post_time))

                semantic_pred = semantic_pred.squeeze(0).cpu().numpy()
                if panoptic_pred is not None:
                    panoptic_pred = panoptic_pred.squeeze(0).cpu().numpy()
                if foreground_pred is not None:
                    foreground_pred = foreground_pred.squeeze(0).cpu().numpy()

                # Crop padded regions.
                image_size = data['size'].squeeze(0).cpu().numpy()
                semantic_pred = semantic_pred[:image_size[0], :image_size[1]]
                if panoptic_pred is not None:
                    panoptic_pred = panoptic_pred[:image_size[0], :image_size[1]]
                if foreground_pred is not None:
                    foreground_pred = foreground_pred[:image_size[0], :image_size[1]]

                # Resize back to the raw image size.
                raw_image_size = data['raw_size'].squeeze(0).cpu().numpy()
                if raw_image_size[0] != image_size[0] or raw_image_size[1] != image_size[1]:
                    semantic_pred = cv2.resize(semantic_pred.astype(np.float), (raw_image_size[1], raw_image_size[0]),
                                               interpolation=cv2.INTER_NEAREST).astype(np.int32)
                    if panoptic_pred is not None:
                        panoptic_pred = cv2.resize(panoptic_pred.astype(np.float),
                                                   (raw_image_size[1], raw_image_size[0]),
                                                   interpolation=cv2.INTER_NEAREST).astype(np.int32)
                    if foreground_pred is not None:
                        foreground_pred = cv2.resize(foreground_pred.astype(np.float),
                                                     (raw_image_size[1], raw_image_size[0]),
                                                     interpolation=cv2.INTER_NEAREST).astype(np.int32)

                # Evaluates semantic segmentation.
                semantic_metric.update(semantic_pred,
                                       data['raw_label'].squeeze(0).cpu().numpy(),
                                       image_filename_list[i])

                # Optional: evaluates instance segmentation.
                if instance_metric is not None:
                    raw_semantic = F.softmax(out_dict['semantic'][:, :, :image_size[0], :image_size[1]], dim=1)
                    center_hmp = out_dict['center'][:, :, :image_size[0], :image_size[1]]
                    if raw_image_size[0] != image_size[0] or raw_image_size[1] != image_size[1]:
                        raw_semantic = F.interpolate(raw_semantic,
                                                     size=(raw_image_size[0], raw_image_size[1]),
                                                     mode='bilinear',
                                                     align_corners=False)  # Consistent with OpenCV.
                        center_hmp = F.interpolate(center_hmp,
                                                   size=(raw_image_size[0], raw_image_size[1]),
                                                   mode='bilinear',
                                                   align_corners=False)  # Consistent with OpenCV.

                    raw_semantic = raw_semantic.squeeze(0).cpu().numpy()
                    center_hmp = center_hmp.squeeze(1).squeeze(0).cpu().numpy()

                    instances = get_cityscapes_instance_format(panoptic_pred,
                                                               raw_semantic,
                                                               center_hmp,
                                                               label_divisor=data_loader.dataset.label_divisor,
                                                               score_type=config.TEST.INSTANCE_SCORE_TYPE)                                 
                    instance_metric.update(instances, image_filename_list[i])

                # Optional: evaluates panoptic segmentation.
                if panoptic_metric is not None:
                    image_id = '_'.join(image_filename_list[i].split('_')[:3])
                    panoptic_metric.update(panoptic_pred,
                                           image_filename=image_filename_list[i],
                                           image_id=image_id)

                # Optional: evaluates foreground segmentation.
                if foreground_metric is not None:
                    semantic_label = data['raw_label'].squeeze(0).cpu().numpy()
                    foreground_label = np.zeros_like(semantic_label)
                    for sem_lab in np.unique(semantic_label):
                        # Both `stuff` and `ignore` are background.
                        if sem_lab in data_loader.dataset.thing_list:
                            foreground_label[semantic_label == sem_lab] = 1

                    # Use semantic segmentation as foreground segmentation.
                    if foreground_pred is None:
                        foreground_pred = np.zeros_like(semantic_pred)
                        for sem_lab in np.unique(semantic_pred):
                            if sem_lab in data_loader.dataset.thing_list:
                                foreground_pred[semantic_pred == sem_lab] = 1

                    foreground_metric.update(foreground_pred,
                                             foreground_label,
                                             image_filename_list[i])

                if config.TEST.DEBUG:
                    # Raw outputs
                    save_debug_images(
                        dataset=data_loader.dataset,
                        batch_images=image,
                        batch_targets=data,
                        batch_outputs=out_dict,
                        out_dir=debug_out_dir,
                        iteration=i,
                        target_keys=config.DEBUG.TARGET_KEYS,
                        output_keys=config.DEBUG.OUTPUT_KEYS,
                        is_train=False,
                    )
                    if panoptic_pred is not None:
                        # Processed outputs
                        save_annotation(semantic_pred, debug_out_dir, 'semantic_pred_%d' % i,
                                        add_colormap=True, colormap=data_loader.dataset.create_label_colormap())
                        pan_to_sem = panoptic_pred // data_loader.dataset.label_divisor
                        save_annotation(pan_to_sem, debug_out_dir, 'pan_to_sem_pred_%d' % i,
                                        add_colormap=True, colormap=data_loader.dataset.create_label_colormap())
                        ins_id = panoptic_pred % data_loader.dataset.label_divisor
                        pan_to_ins = panoptic_pred.copy()
                        pan_to_ins[ins_id == 0] = 0
                        save_instance_annotation(pan_to_ins, debug_out_dir, 'pan_to_ins_pred_%d' % i)

                        save_panoptic_annotation(panoptic_pred, debug_out_dir, 'panoptic_pred_%d' % i,
                                                 label_divisor=data_loader.dataset.label_divisor,
                                                 colormap=data_loader.dataset.create_label_colormap())
    except Exception:
        logger.exception("Exception during testing:")
        raise
    finally:
        logger.info("Inference finished.")
        semantic_results = semantic_metric.evaluate()
        logger.info(semantic_results)
        if instance_metric is not None:
            instance_results = instance_metric.evaluate()
            logger.info(instance_results)
        if panoptic_metric is not None:
            panoptic_results = panoptic_metric.evaluate()
            logger.info(panoptic_results)
        if foreground_metric is not None:
            foreground_results = foreground_metric.evaluate()
            logger.info(foreground_results)


if __name__ == '__main__':
    main()

**Comment by bowenc0221** [comment]
I slightly modified your code and created a PR for it: #29
