### ISSUE TITLE
Demo code did not work out.

### ISSUE THREAD

**Issue by Metal-joker** [bowenc0221/panoptic-deeplab#26]
I used this command as README suggested
`python3.7 tools/demo.py --cfg configs/panoptic_deeplab_R50_os32_cityscapes.yaml --input-files ./data/test/  --output-dir ./data/output/ TEST.MODEL_FILE panoptic_deeplab_R50_os32_cityscapes.pth`

I have installed all dependencies but still got this error:
```Traceback (most recent call last):
  File "tools/demo.py", line 315, in <module>
    main()
  File "tools/demo.py", line 128, in main
    data_loader = build_test_loader_from_cfg(config)
  File "/data/side/panoptic-deeplab/tools/../segmentation/data/build.py", line 142, in build_test_loader_from_cfg
    dataset = build_dataset_from_cfg(config, is_train=False)
  File "/data/side/panoptic-deeplab/tools/../segmentation/data/build.py", line 83, in build_dataset_from_cfg
    **dataset_cfg[config.DATASET.DATASET]
  File "/data/side/panoptic-deeplab/tools/../segmentation/data/datasets/cityscapes_panoptic.py", line 67, in __init__
    scale_step_size, mean, std)
  File "/data/side/panoptic-deeplab/tools/../segmentation/data/datasets/cityscapes.py", line 84, in __init__
    assert len(self) == _CITYSCAPES_INFORMATION.splits_to_sizes[self.split]
AssertionError
```
I have tried to disable this assert, but still, I got another error:
```Traceback (most recent call last):
  File "tools/demo.py", line 315, in <module>
    main()
  File "tools/demo.py", line 128, in main
    data_loader = build_test_loader_from_cfg(config)
  File "/data/side/panoptic-deeplab/tools/../segmentation/data/build.py", line 142, in build_test_loader_from_cfg
    dataset = build_dataset_from_cfg(config, is_train=False)
  File "/data/side/panoptic-deeplab/tools/../segmentation/data/build.py", line 83, in build_dataset_from_cfg
    **dataset_cfg[config.DATASET.DATASET]
  File "/data/side/panoptic-deeplab/tools/../segmentation/data/datasets/cityscapes_panoptic.py", line 88, in __init__
    dataset = json.load(open(json_filename))
FileNotFoundError: [Errno 2] No such file or directory: './datasets/cityscapes/gtFine/cityscapes_panoptic_val_trainId.json'
````

Any help?

**Comment by bowenc0221** [comment]
It seems like you did not run `python cityscapesscripts/preparation/createPanopticImgs.py --use-train-id` to generate label with trainid.

https://github.com/bowenc0221/panoptic-deeplab/tree/master/datasets#expected-dataset-structure-for-cityscapes

**Comment by Metal-joker** [comment]
Is this demo about to produce results of the CityScapes test-set? Is there any way I can test my own image with your pretrained model?
P.S. I did run this `python cityscapesscripts/preparation/createPanopticImgs.py --use-train-id` command as you said, but after I install cityscapescript, it still have no such file error.

**Comment by bowenc0221** [comment]
The demo code is aimed for testing any image, the reason it still uses the dataloader is because I will need the colormap from Cityscapes dataset (I'm just too lazy to modify that part).

Do you mean it does not generate `./datasets/cityscapes/gtFine/cityscapes_panoptic_val_trainId.json` with `python cityscapesscripts/preparation/createPanopticImgs.py --use-train-id` or you do not have `cityscapesscripts/preparation/createPanopticImgs.py`?

You can either clone the `cityscapesscripts` repo or run `python -m cityscapesscripts/preparation/createPanopticImgs --use-train-id`. But the `cityscapesscripts` is a little hard to use, you need to be careful on how to setup the CITYSCAPES data path.

**Comment by bowenc0221** [comment]
Hi @Metal-joker 
I updated demo code in #28 so it does not require Cityscapes dataset anymore.
Please try again to see if there is still any error.

I also introduced a new flag `--merge-image` to make visualization looks better.

**Comment by Metal-joker** [comment]
It works!
Thanks for your help!
Excellent work!
