### ISSUE TITLE
Why using 4 GPUs is slower than 1 GPU

### ISSUE THREAD

**Issue by BoChengTsai** [bowenc0221/panoptic-deeplab#32]
Hello, I would like to ask why using 4 GPUs is slower than 1 GPU.
Please see the attached pictures(Time).

4GPUs
![image](https://user-images.githubusercontent.com/27048900/88537410-1eb6c400-d040-11ea-8809-438981e57fa4.png)

1GPU
![image](https://user-images.githubusercontent.com/27048900/88537357-0777d680-d040-11ea-91b1-fa515a4805e4.png)

Thank you

**Comment by bowenc0221** [comment]
What batch size are you using for 4GPUs and 1 GPU?

**Comment by BoChengTsai** [comment]
I set IMS_PER_BATCH=4 for 4GPUs, and IMS_PER_BATCH=16 for 1 GPU.

Thank you

**Comment by bowenc0221** [comment]
IMS_PER_BATCH=4 for 4GPUs or IMS_PER_BATCH=16 for 4GPUs?
IMS_PER_BATCH is not the per GPU batchsize.

if you set IMS_PER_BATCH=4 for 4GPUs, and IMS_PER_BATCH=16 for 1 GPU, then the batchsize are different.

Are you using PCIe or NVLink to connect GPUs? Have you tested the communication speed between GPUs?

**Comment by BoChengTsai** [comment]
Sorry, I set the wrong IMS_PER_BATCH=4 for 4 GPUs, thank you for your reminder.

No, I didn't use PCle or NVLind.
If needed, I will install it and try again.

Thank you
