### ISSUE TITLE
question about semantic segmentation

### ISSUE THREAD

**Issue by blackmagicianZ** [bowenc0221/panoptic-deeplab#35]
Thanks for the code! If I only want to train semantic segmentation, Can I use this yaml `configs/Misc/Base-Semantic-DeepLab.yaml`, Do I need to modify it? @bowenc0221

**Comment by bowenc0221** [comment]
Please modify `configs/panoptic_deeplab_R50_os32_cityscapes.yaml` according to `configs/Misc/Base-Semantic-DeepLab.yaml`.

`configs/Misc/Base-Semantic-DeepLab.yaml` won't give good results for semantic segmentation.
