### ISSUE TITLE
about input possible bug?

### ISSUE THREAD

**Issue by pingjun18-li** [bowenc0221/panoptic-deeplab#36]
Hi, bowen,
In segmentation\data\datasets\base_dataset.py, line 119-121, dataset_dict['semantic'] directly uses label, where the values are original id (not trainId).
This seems not consistent with the dataset_dict['semantic'] value set in line 127 (in fact assigned inside self.target_transform), where trainId is used.
Is this a bug?
Of course this has no effect for the panoptic dataset because hasInstance is set to True, e.g. in class CityscapesPanoptic.
Also, I wonder what is the case that line 191-121 will be used.

**Comment by bowenc0221** [comment]
There is a [Cityscapes semantic segmentation dataset](https://github.com/bowenc0221/panoptic-deeplab/blob/master/segmentation/data/datasets/cityscapes.py) that will load semantic trainid labels, you can use this dataset to train semantic segmentation model only (e.g. DeepLabv3 and DeepLabv3+).

Originally I want to make it a segmentation toolbox that support both semantic and panoptic segmentation, but I'm just too lazy...
