### ISSUE TITLE
 No such file or directory: './datasets/cityscapes/gtFine/cityscapes_panoptic_train_trainId.json'

### ISSUE THREAD

**Issue by wudongyuan** [bowenc0221/panoptic-deeplab#37]
Hi, bowen,
I ran into this problem when training with the cityscapes dataset. How should this file be generated?
Thanks!

**Comment by bowenc0221** [comment]
Please run the following commands to generate panoptic annotations for Cityscapes dataset:
```
CITYSCAPES_DATASET=/path/to/cityscapes python cityscapesscripts/preparation/createTrainIdLabelImgs.py --use-train-id
CITYSCAPES_DATASET=/path/to/cityscapes python cityscapesscripts/preparation/createTrainIdLabelImgs.py
```

You can find it here: https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/preparation/createPanopticImgs.py

**Comment by wudongyuan** [comment]
That's it, thank you very much!
