### ISSUE TITLE
RuntimeError: Address already in use

### ISSUE THREAD

**Issue by AgarwalVedika** [bowenc0221/panoptic-deeplab#38]
Hi,

I am using the initial version, hence training the model using:
_python -m torch.distributed.launch --nproc_per_node=4 tools/train_net.py --cfg configs/Base-Panoptic-DeepLab.yaml_

However, I often get the "Address already in use" RuntimeError while using 4 gpus for multi-processing. 

_File "/home/agarwalv/miniconda3/envs/panoptic_deeplab/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 172, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout)
RuntimeError: Address already in use_

What can I do to fix this?
Moreover, also are there significant changes compared to the initial version that I should be worried about?

**Comment by bowenc0221** [comment]
It seems this error is caused by the PyTorch distributed package, you can try a different address or port: https://github.com/pytorch/pytorch/blob/master/torch/distributed/launch.py#L173

I would suggest you use [this config](https://github.com/bowenc0221/panoptic-deeplab/blob/master/configs/panoptic_deeplab_R50_os32_cityscapes.yaml). Somehow os=16 does not work with my code.

**Comment by AgarwalVedika** [comment]
Hi, Yes that indeed fixed the bug; key is to also specify the master_port :) 
_python -m torch.distributed.launch --nproc_per_node=4 **--master_port=9907** tools/train_net.py --cfg configs/Base-Panoptic-DeepLab_bepscapes_1.yaml_
I have been using _Base-Panoptic-DeepLab_bepscapes_1.yaml_ for some time, in fact built my modifications on top of it- no os problems so far...

**Comment by bowenc0221** [comment]
os=16 means the encoder output stride (os) is 16. I found os=16 gives worse performance than os=32. Setting os=16 requires to use dilated convolution in the last stage of ResNet (res5), so I'm not sure if there is any bug in that part or not.

The major differences between two configs are shown in image below. I would suggest you use the left one (os=32 setting).

<img width="1877" alt="Screen Shot 2020-08-28 at 3 32 20 PM" src="https://user-images.githubusercontent.com/25308473/91620029-acd5e100-e943-11ea-95cb-0d2bc90a8748.png">
