### ISSUE TITLE
Lightweighted models

### ISSUE THREAD

**Issue by jinfagang** [bowenc0221/panoptic-deeplab#40]
Any lightweighted models provided or experimented?

**Comment by bowenc0221** [comment]
Please check https://github.com/bowenc0221/panoptic-deeplab/blob/master/MODEL_ZOO.md, I have MobileNet model available.

<img width="642" alt="Screen Shot 2020-08-28 at 3 34 20 PM" src="https://user-images.githubusercontent.com/25308473/91620146-f292a980-e943-11ea-80aa-966aa3eaec04.png">

**Comment by jinfagang** [comment]
@bowenc0221 Would u like add run speed for references in terms of different backbones?
