### ISSUE TITLE
what's the meaning of the colormap number？

### ISSUE THREAD

**Issue by 695874419** [bowenc0221/panoptic-deeplab#42]
![image](https://user-images.githubusercontent.com/28133682/92364025-02b93e80-f125-11ea-8d74-9925f57774d6.png)

**Comment by WZTENG** [comment]
RGB color of class

**Comment by 695874419** [comment]
But, what is the semantics of color?

**Comment by WZTENG** [comment]
https://github.com/bowenc0221/panoptic-deeplab/blob/5b3dd8c127f4de75c2f1bbe380bd656fa3cdd941/tools/demo.py#L102-L127

**Comment by bowenc0221** [comment]
@695874419 It is the official colormap for CItyscapes dataset, here is the mapping from class index to class name.
```
0, "road"
1, "sidewalk"
2, "building"
3, "wall"
4, "fence"
5, "pole"
6, "traffic light"
7, "traffic sign"
8, "vegetation"
9, "terrain"
10, "sky"
11, "person"
12, "rider"
13, "car"
14, "truck"
15, "bus"
16, "train"
17, "motorcycle"
18, "bicycle"
```
