### ISSUE TITLE
Saving instances in txt?

### ISSUE THREAD

**Issue by tiberium24** [bowenc0221/panoptic-deeplab#43]
Hello,

I would like to be able to save object instances in a .txt in the format of:
class confidence xmin xmax ymin ymax
That means similar to object detection. Is it possible?

**Comment by bowenc0221** [comment]
Yes, you can check this code: https://github.com/bowenc0221/panoptic-deeplab/blob/5b3dd8c127f4de75c2f1bbe380bd656fa3cdd941/segmentation/model/post_processing/evaluation_format.py#L11

`xmin xmax ymin ymax` can be easily calculated from the predicted mask.
