### ISSUE TITLE
Understanding num of GPUs and the images per batch during training

### ISSUE THREAD

**Issue by AgarwalVedika** [bowenc0221/panoptic-deeplab#44]
Hi,
I am a noob when it comes to multi-processing and all. Wanted to ask- what does it mean when we set the number of threads to 4, and use TRAIN.IMS_PER_BATCH = 4? Is it equivalent to having a mini-batch size of 1? Or would it be 4? I did run my experiments with a single GPU and TRAIN.IMS_PER_BATCH = 1; it gave really worse performance.

**Comment by Wastoon** [comment]
> Hi,
> I am a noob when it comes to multi-processing and all. Wanted to ask- what does it mean when we set the number of threads to 4, and use TRAIN.IMS_PER_BATCH = 4? Is it equivalent to having a mini-batch size of 1? Or would it be 4? I did run my experiments with a single GPU and TRAIN.IMS_PER_BATCH = 1; it gave really worse performance.

Me too, when I try to use single_GPU, the final eval-results are quite bad.

**Comment by Wastoon** [comment]
> Hi,
> I am a noob when it comes to multi-processing and all. Wanted to ask- what does it mean when we set the number of threads to 4, and use TRAIN.IMS_PER_BATCH = 4? Is it equivalent to having a mini-batch size of 1? Or would it be 4? I did run my experiments with a single GPU and TRAIN.IMS_PER_BATCH = 1; it gave really worse performance.

Try the method here:https://github.com/bowenc0221/panoptic-deeplab/issues/34#issuecomment-670323465

**Comment by bowenc0221** [comment]
TRAIN.IMS_PER_BATCH is the batchsize independent on how many GPUs you use, check this https://github.com/bowenc0221/panoptic-deeplab/blob/5b3dd8c127f4de75c2f1bbe380bd656fa3cdd941/segmentation/data/build.py#L108
