### ISSUE TITLE
No module named 'detectron2.projects'

### ISSUE THREAD

**Issue by chenerg** [bowenc0221/panoptic-deeplab#54]
I install detectron2 with 
`python -m pip install detectron2 -f \
  https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.6/index.html`, 
however, when I run train_panoptic_deeplab.py, I met the error 
`No module named 'detectron2.projects'`, do you have any idea?

**Comment by bowenc0221** [comment]
Hi @chenerg 
You will need to build detectron2 from source, I think the binary you are using is compiled before Panoptic-DeepLab is in Detectron2.

**Comment by chenerg** [comment]
Thanks, I will give a try.

**Comment by bowenc0221** [comment]
FYI, you can use the latest pre-built Detectron2 (v0.3) now: https://github.com/facebookresearch/detectron2/releases/tag/v0.3
