### ISSUE TITLE
Training on one GPU with IMS_PER_GPU > 1

### ISSUE THREAD

**Issue by cvcore** [bowenc0221/panoptic-deeplab#55]
Hi @bowenc0221 ,

I'm currently using the code from the older branch (5b3dd8c, since our code builds on top of it) and trying to retrain the model with `panoptic_deeplab_R50_os32_cityscapes` as configuration. Since our GPU memory is enough (24G each), I'm trying to have `images_per_worker` larger than 1. 
Unfortunately this will give an error of:

```
Original Traceback (most recent call last):
  File "site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "site-packages/torch/utils/data/_utils/collate.py", line 73, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "site-packages/torch/utils/data/_utils/collate.py", line 73, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "site-packages/torch/utils/data/_utils/collate.py", line 81, in default_collate
    raise RuntimeError('each element in list of batch should be of equal size')
RuntimeError: each element in list of batch should be of equal size
```

the command I used for training is:
```
CUDA_VISIBLE_DEVICES="2" python tools/train_net.py --cfg configs/panoptic_deeplab_R50_os32_cityscapes.yaml DATASET.ROOT ~/forecasting-c/dataset/cityscapes TRAIN.IMS_PER_BATCH 4 GPUS '(1,)'
```

My questions are:

1. Will >1 batch pro GPU be supported in the current code?
2. If yes, what part of the code do I need to change?

Thanks in advance!

**Comment by bowenc0221** [comment]
AFAIK, >1 batch per GPU is supported (see #34). Are you using the Cityscapes panoptic dataset? From the error message it looks like some error due to dataloader.

BTW, I think you should use `GPUS '(0,)'` since you add `CUDA_VISIBLE_DEVICES="2"`.

**Comment by cvcore** [comment]
Actually it was because from PyTorch 1.6 on the behavior of `default_collate` changed and in `cityscapes_panoptic` dataset its `center_points` field for different samples is usually different, causing this error.

To solve it, use either of these two options:

1. Downgrade PyTorch to 1.6 as in https://github.com/pytorch/pytorch/issues/42654
2. Comment out the center_points field in https://github.com/bowenc0221/panoptic-deeplab/blob/deprecated/segmentation/data/transforms/target_transforms.py#L153 since we don't need it during training.

I leave it here in case anyone runs into the same issue.

**Comment by ding-Chen** [comment]
@cvcore ,hi, I encountered the same error, but unfortunately I couldn't reduce the pytorch version to 1.6.0, so I wanted to use the second method. Will the second method affect the test results. Or is it necessary to comment out that sentence during training and restore it when testing?
