### ISSUE TITLE
Can't find the dilation rate setting in Backbone

### ISSUE THREAD

**Issue by CuberrChen** [bowenc0221/panoptic-deeplab#58]
hi!your work is so good. but when i check the code that you released, i can't find the dilation rate setting in the backbone,while the paper indicates: "The encoder backbone is adapted
from an ImageNet-pretrained neural network paired with atrous convolution for extracting denser feature maps in its last block. "
Did I get it wrong?
Looking forward to your help.
Good luck.

**Comment by bowenc0221** [comment]
Check this: https://github.com/facebookresearch/detectron2/blob/14e53b54ab7fec738ba3d437074d17db5fb6cee9/projects/Panoptic-DeepLab/configs/Cityscapes-PanopticSegmentation/panoptic_deeplab_R_52_os16_mg124_poly_90k_bs32_crop_512_1024.yaml#L11

It is only supported in the Detectron2 version.
