### ISSUE TITLE
Can't correctly crop the coco image

### ISSUE THREAD

**Issue by moodlife** [bowenc0221/panoptic-deeplab#59]
@bowenc0221 Hi！I found that in the D2 version, I can only crop the COCO to 1024, But I want to crop it to 1025 according to the paper. How can I deal with this issue. And I wang to randomcrop the image as you did in the old version code, but the D2 can only crop the image into a smaller image, and it can't random pad the ori img. I wonder if you can give me some advice.
Sincerely.

**Comment by bowenc0221** [comment]
The entire D2 is built to deal with even image size AFAIK, so it will require changing a lot of code to support odd image size (it means you might need to check every file in D2).

For random cropping, it is not supported in D2 yet. You will need to do random cropping by yourself in DatasetMapper.

**Comment by bowenc0221** [comment]
COCO models are now available.
