### ISSUE TITLE
Training panoptic segmentation for a custom dataset in coco-panoptic format

### ISSUE THREAD

**Issue by koushik-n** [bowenc0221/panoptic-deeplab#61]
1) Could you please tell if register_coco_panoptic  function in https://github.com/facebookresearch/detectron2/blob/master/detectron2/data/datasets/coco_panoptic.py be used to register a custom dataset in coco-panoptic format? I can generate the following files for the training and validation of custom dataset.
image_root (str): directory which contains all the images
panoptic_root (str): directory which contains panoptic annotation images
 panoptic_json (str): path to the json panoptic annotation file
instances_json (str): path to the json instance annotation file

2)  Should we create panoptic_{train,val}2017_trainId.json for registering a custom dataset in coco-panoptic format ?.  Because, the register_coco_panoptic function doesn't  seem use to use these  panoptic_{train,val}2017_trainId.json files.

**Comment by bowenc0221** [comment]
The register_coco_panoptic in Detectron2 uses the original COCO panoptic json file. As long as you have the correct metadata to map category index to 0~N it should be fine: https://github.com/facebookresearch/detectron2/blob/0d72f4397f4e49e4f7c093906600c97810079f1d/detectron2/data/datasets/coco_panoptic.py#L26-L37

More detail should be in the documentation: https://detectron2.readthedocs.io/tutorials/datasets.html

**Comment by koushik-n** [comment]
1) Could you please tell if you use the PanopticFPN data format for COCO panoptic segmentation in your project. If yes, then should  I be using  register_coco_panoptic_separated for the custom dataset as it will also register the sem_seg_root (directory which contains all the ground truth segmentation annotations). 

2)  I have separate json files for  instance segementation and semantic segmentation for my custom dataset  in coco format.  Can I load the dataset_dicts from them and use this merge_to_panoptic https://github.com/facebookresearch/detectron2/blob/0d72f4397f4e49e4f7c093906600c97810079f1d/detectron2/data/datasets/coco_panoptic.py#L169 to create the coco_panoptic json file?.

**Comment by bowenc0221** [comment]
> 1. Could you please tell if you use the PanopticFPN data format for COCO panoptic segmentation in your project. If yes, then should I be using register_coco_panoptic_separated for the custom dataset as it will also register the sem_seg_root (directory which contains all the ground truth segmentation annotations).

We use the `register_coco_panoptic`, not using PanopticFPN data format.

> 2. I have separate json files for instance segementation and semantic segmentation for my custom dataset in coco format. Can I load the dataset_dicts from them and use this merge_to_panoptic https://github.com/facebookresearch/detectron2/blob/0d72f4397f4e49e4f7c093906600c97810079f1d/detectron2/data/datasets/coco_panoptic.py#L169 to create the coco_panoptic json file?.

No, your custom json dataset should have the same format as original COCO panoptic format. Otherwise you will need to modify the dataset mapper to make sure this get the same input arguement: https://github.com/facebookresearch/detectron2/blob/0d72f4397f4e49e4f7c093906600c97810079f1d/projects/Panoptic-DeepLab/panoptic_deeplab/dataset_mapper.py#L113

**Comment by koushik-n** [comment]
Okay thanks. 
> 2\. Should we create panoptic_{train,val}2017_trainId.json for registering a custom dataset in coco-panoptic format ?.  Because, the register_coco_panoptic function doesn't  seem to use these  panoptic_{train,val}2017_trainId.json files for registration.

**Comment by bowenc0221** [comment]
`panoptic_{train,val}2017_trainId.json` is not needed because tranid is generated in register_coco_panoptic

**Comment by koushik-n** [comment]
okay thanks
