### ISSUE TITLE
RuntimeError: each element in list of batch should be of equal size

### ISSUE THREAD

**Issue by CuberrChen** [bowenc0221/panoptic-deeplab#62]
hi！i'm trying to understand your code。but when i run " p`ython -m torch.distributed.launch --nproc_per_node=2 train_net.py --cfg ../configs/panoptic_deeplab_MBNV2_100_os32_cityscapes_bs16_lr_x2.yaml` "  as your README,the error happend! can you help me? i didn't do anything to the code.

**Comment by bowenc0221** [comment]
Which PyTorch version are you using? Can you try 1.5.0 as mentioned here: https://github.com/pytorch/pytorch/issues/42654

**Comment by CuberrChen** [comment]
thanks!  it is the reason of Pytoch version!
