### ISSUE TITLE
 custom coco format panoramic segmentation dataset

### ISSUE THREAD

**Issue by wshilaji** [bowenc0221/panoptic-deeplab#63]
Do you kown how to create wwn custom coco format panoramic segmentation dataset? for examlple panoramic_{}2017.json.
I would appreciate it if you could help me

**Comment by bowenc0221** [comment]
Please follow Detectron2 document for registering custom dataset: https://detectron2.readthedocs.io/tutorials/datasets.html

COCO format for panoptic segmentation is here: https://cocodataset.org/#format-data

**Comment by mvdelt** [comment]
@bowenc0221  I think what @wshilaji tried to ask was "how to create custom annotations for COCO panoptic format".
I also have the same question. 
Is there any decent tool for custom panoptic annotation? (into COCO format or Cityscapes format)
There are many annotation/labeling tools for object detection or semantic segmentation, 
but I haven't found one for panoptic segmentation.

**Comment by bowenc0221** [comment]
AFAIK there are no open-sourced labeling tools for panoptic annotation. All panoptic segmentation datasets are created from existing semantic and instance annotations.

**Comment by mvdelt** [comment]
@bowenc0221  Thanks.
So it is possible to make custom panoptic annotation by making semantic & instance annotations with existing labeling tools and then convert them into panoptic annotation? 
Is there any script for converting semantic & instance annotations to panoptic annotation? 
I wanna train Panoptic Deeplab with my custom dataset... Thank you in advance :)

**Comment by bowenc0221** [comment]
https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/preparation/createPanopticImgs.py

**Comment by wshilaji** [comment]
> @bowenc0221 


 I have solved the problem. I wrote my own script in the COCO format with  the labelme annotation tool.

**Comment by LiWentomng** [comment]
@wshilaji  I also have the same question for converting converting semantic & instance annotations to panoptic annotation. Can you provide your script with some instructions in your github?  I will star it.   I would appreciate it if you could help me.

**Comment by wshilaji** [comment]
> 
https://github.com/wshilaji/panoptic_coco_scipt . 
The instruction manual is not detailed. You can reseach code  for a while .
COCO format for panoptic segmentation is here: https://cocodataset.org/#format-data

**Comment by wshilaji** [comment]
> 
@LiWentomng
https://github.com/wshilaji/panoptic_coco_scipt .
The instruction manual is not detailed. You can reseach code for a while .
COCO format for panoptic segmentation is here: https://cocodataset.org/#format-data

**Comment by LiWentomng** [comment]
@wshilaji Thanks a lot!

**Comment by userwatch** [comment]
Hello @mvdelt , I am trying to train Panoptic with my custom data. How did you create the panoptic annotation? Please help me.
