### ISSUE TITLE
How to generate json files?

### ISSUE THREAD

**Issue by LiXiAng9867** [bowenc0221/panoptic-deeplab#66]
Hello, thank you for sharing this great work.

I am trying to reproduce some results on Cityscapes dataset. And I didn't find any files that can generate json file in COCO format. Does the current codebase support to generate json file for submitting? Thank you.

**Comment by bowenc0221** [comment]
Do you mean the training annotation json files? They are generated by `CITYSCAPES_DATASET=/path/to/abovementioned/cityscapes python cityscapesscripts/preparation/createPanopticImgs.py`, please read the README for more detail.

**Comment by LiXiAng9867** [comment]
Thank you for your reply. While I mean how to generate json files from the prediction results?

**Comment by LiXiAng9867** [comment]
> Do you mean the training annotation json files? They are generated by `CITYSCAPES_DATASET=/path/to/abovementioned/cityscapes python cityscapesscripts/preparation/createPanopticImgs.py`, please read the README for more detail.

Thank you for your reply. While I mean how to generate json files from the prediction results? I am trying to reproduce results with MV and pseudo labels (naive-student) on Cityscapes. I hope to iteratively train the model so I need to prepare the output predicts have the same format as COCO format annotations. Is there any sources can be referred? Thank you!

**Comment by bowenc0221** [comment]
This file (https://github.com/bowenc0221/panoptic-deeplab/blob/master/segmentation/evaluation/panoptic.py) writes prediction to json for evaluation.
