### ISSUE TITLE
what i should do to resolve this error

### ISSUE THREAD

**Issue by ppl520zfl** [bowenc0221/panoptic-deeplab#7]
Hi,Bowen,Thanks for your code!
I try to reproduce the Ciytyscapes number ,but when i run train_net.py,
an error occurs:
  Traceback (most recent call last):
     File "tools/train_net.py", line 191, in <module>
       main()
     File "tools/train_net.py", line 185, in main
      torch.save(model.module.state_dict(),
      File "/home/ppl/anaconda3/envs/panoptic-deeplab/lib/python3.6/site- 
    packages/torch/nn/modules/module.py", line 576, in __getattr__
          type(self).__name__, name))
    AttributeError: 'PanopticDeepLab' object has no attribute 'module'
Can you tell me what i should do to  solve the problem?

**Comment by bowenc0221** [comment]
From the error message, it is caused by not using DDP. Did you use `torch.distributed.launch` to launch `tools/train_net.py`?

**Comment by ppl520zfl** [comment]
> From the error message, it is caused by not using DDP. Did you use `torch.distributed.launch` to launch `tools/train_net.py`?

I just try it on my own computer with 1 gpu ,maybe i should run on the  cloud server .
Thank you!

**Comment by bowenc0221** [comment]
You can also remove `module` in these 2 lines:
https://github.com/bowenc0221/panoptic-deeplab/blob/master/tools/train_net.py#L176
https://github.com/bowenc0221/panoptic-deeplab/blob/master/tools/train_net.py#L185

`model.module.state_dict()` => `model.state_dict()`

**Comment by ppl520zfl** [comment]
Thank you so much！
