### ISSUE TITLE
Ordered Dictionary Error (.pkl) and Gibberish Random Output!

### ISSUE THREAD

**Issue by veer5551** [bowenc0221/panoptic-deeplab#78]
Hello,

Thanks for this Project!
I Just started exploring the Deeplab-panoptic detectron2
I am facing 2 issues currently.

A. I am getting this error for all the h48.pkl converted models.
```
(detectron2) C:\Workspace\msjmf59\VirtualEnvironments\detectron2\Deeplab_d2\panoptic-deeplab\tools_d2>python demo.py --config-file configs\Cityscapes-PanopticSegmentation\panoptic_deeplab_H_48_os16_mg124_poly_90k_bs32_crop_512_1024.yaml --input res_29.jpg
[32m[02/22 17:42:30 detectron2]: [0mArguments: Namespace(confidence_threshold=0.5, config_file='configs\\Cityscapes-PanopticSegmentation\\panoptic_deeplab_H_48_os16_mg124_poly_90k_bs32_crop_512_1024.yaml', input=['res_29.jpg'], opts=[], output=None, video_input=None, webcam=False)
[32m[02/22 17:42:35 fvcore.common.checkpoint]: [0mLoading checkpoint from h48.pkl
[32m[02/22 17:42:36 fvcore.common.checkpoint]: [0mReading a file from 'third_party'
Traceback (most recent call last):
  File "demo.py", line 82, in <module>
    demo = VisualizationDemo(cfg)
  File "C:\Workspace\msjmf59\VirtualEnvironments\detectron2\Deeplab_d2\panoptic-deeplab\tools_d2\d2\predictor.py", line 35, in __init__
    self.predictor = DefaultPredictor(cfg)
  File "c:\workspace\msjmf59\virtualenvironments\detectron2\detectron2\detectron2\engine\defaults.py", line 194, in __init__
    checkpointer.load(cfg.MODEL.WEIGHTS)
  File "C:\Workspace\msjmf59\VirtualEnvironments\detectron2\lib\site-packages\fvcore\common\checkpoint.py", line 123, in load
    incompatible = self._load_model(checkpoint)
  File "c:\workspace\msjmf59\virtualenvironments\detectron2\detectron2\detectron2\checkpoint\detection_checkpoint.py", line 61, in _load_model
    self._convert_ndarray_to_tensor(checkpoint["model"])
  File "C:\Workspace\msjmf59\VirtualEnvironments\detectron2\lib\site-packages\fvcore\common\checkpoint.py", line 302, in _convert_ndarray_to_tensor
    "Unsupported type found in checkpoint! {}: {}".format(k, type(v))
ValueError: Unsupported type found in checkpoint! model: <class 'collections.OrderedDict'>
```
Am I missing something here. 

B. And when I run the X65 models on sample images, I am getting a random gibberish output like this.
And I am sure I am definitely doing something not to be :p

![image](https://user-images.githubusercontent.com/41330355/108707293-cc864480-7535-11eb-9547-fdcc9e1f4ece.png)

Some noobs questions,
1. Do we have to crop/preprocess the image and then feed to model. (what are the input sizes)
I got pool_kernel_error while feeding direct images. However it runs after resizing to 640x640, 1024x2048.
2. How do we change the model names to be taken via the config. It take the default X65.pkl / h48.pkl.
Have to replace every time curently.

Thanks a lot!

**Comment by bowenc0221** [comment]
I think you are running visualization on a randomly initialized model (h48.pkl and x65.pkl are ImageNet pre-trained weights).

For demo, you do not need to convert the checkpoint `*.pth` (after you download them from Google drive) to `*.pkl`.

**Comment by veer5551** [comment]
Thanks,
Will check and keep you posted!
