### ISSUE TITLE
Feature Request: Add inference-only to train_net.py

### ISSUE THREAD

**Issue by cmarkle85** [bowenc0221/panoptic-deeplab#82]
I have been trying to execute one of your models using the detectron2 framework against the cityscapes demoVideo dataset. That dataset is unannotated and I would like to use Panoptic-DeepLab to generate those annotations. I have the dataset registered with the detectron2 framework and I'm using the most of the metadata from the cityscapes-fine dataset. I'm not sure how to generate (and persist) the annotations. I was hoping you could create an inference-only path in train_net.py that would persist the results.

**Comment by bowenc0221** [comment]
Detectron2 already has a `--eval-only` flag. Is this what you are looking for?

**Comment by cmarkle85** [comment]
I don't think so. The --eval-only mode returns only the evaluation metrics (it looks like it generates the predicted outputs but saves them to a tempfile that gets erased). I don't have ground truth labels for my dataset. I'm trying to use one of your pretrained models to generate the semantic and instance maps.

**Comment by bowenc0221** [comment]
In this case, you will need to write or modify the evaluation metric to save your outputs.
