### ISSUE TITLE
about 'unlabeled' category in Detectron2

### ISSUE THREAD

**Issue by mvdelt** [bowenc0221/panoptic-deeplab#84]
in Detectron2 builtin_meta.py, 
`CITYSCAPES_CATEGORIES` doesn't contain the 'unlabeled' category.
only foreground categories are registered. 

So, IMHO, when inference, there should be some 'threshold' to determine the background,
such as `ROI_HEADS.SCORE_THRESH_TEST`, isn't it?

If there is no threshold, the background would be covered with other categories.

How can we set the threshold?

**Comment by bowenc0221** [comment]
There is no background class in Cityscapes, all 'unlabeled' categories are ignored in evaluation. Please check the [Citysacpes official evaluation code](https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/evaluation/evalPanopticSemanticLabeling.py) for more detail.

**Comment by mvdelt** [comment]
Checked the evaluation code, you're right. Thanks!
