### ISSUE TITLE
Error in loading pickle weights

### ISSUE THREAD

**Issue by 1201amit** [bowenc0221/panoptic-deeplab#86]
I am getting runtime error("Invalid magic number; corrupt file?") while loading pickle weights.

**Comment by suyuzhang** [comment]
I have the same problem.
@bowenc0221 Can you provide a .pth pre-trained model of ResNet52 for cityscapes panoptic segmentation?
Thanks!

**Comment by 1201amit** [comment]
The issue is that panoptic-deeplab (this workspace) and detectron2 Panoptic-DeepLab have different key values in model parameters and given weights follow detectron2 keys. Best way is to create a model using detectron2 Panoptic-DeepLab.

**Comment by bowenc0221** [comment]
@suyuzhang 

The `.pkl` file for ResNet52 is converted from this code: https://github.com/facebookresearch/detectron2/blob/master/tools/convert-torchvision-to-d2.py

The `model` field is the corresponding `.pth` weights with some key conversion.
