### ISSUE TITLE
Train model Error: Unknown LR scheduler: WarmupPolyLR

### ISSUE THREAD

**Issue by guoxuerui** [bowenc0221/panoptic-deeplab#90]
Hi Bowen, we occurred with error in LR scheduler setting. The problem is WarmupPolyLR is originally defined in [DeepLab/build_solver](https://github.com/facebookresearch/detectron2/blob/master/projects/DeepLab/deeplab/build_solver.py) but not involved in [detectron2/solver/build](https://github.com/facebookresearch/detectron2/blob/master/detectron2/solver/build.py). May I ask is there a way to use LR scheduler from the DeepLab separately? even if there's no such an option built yet in the solver of the whole detectron2 library?

**Comment by bowenc0221** [comment]
Please check Panoptic-DeepLab example:
you can import it [like this](https://github.com/facebookresearch/detectron2/blob/c68491acd5e8de57a86b34604ba849c6d55f454b/projects/Panoptic-DeepLab/train_net.py#L25)
and use it [like this](https://github.com/facebookresearch/detectron2/blob/c68491acd5e8de57a86b34604ba849c6d55f454b/projects/Panoptic-DeepLab/train_net.py#L104-L109)

**Comment by guoxuerui** [comment]
It works! thanks
