### ISSUE TITLE
using demo.py to predict an image,But it's all black

### ISSUE THREAD

**Issue by xukaiyan** [bowenc0221/panoptic-deeplab#92]
python demo.py --cfg /home/lab716/seagate8T/jinyishu/panoptic-deeplab-master/configs/panoptic_deeplab_R101_os32_cityscapes.yaml --input-files /home/lab716/seagate8T/jinyishu/panoptic-deeplab-master/tools/   --output-dir ../output TEST.MODEL_FILE panoptic_deeplab_R101_os32_cityscapes.pth
 
But it's all black!
![panoptic_to_instance_pred_0](https://user-images.githubusercontent.com/35806085/123436634-66075500-d601-11eb-90b9-4e32a2793788.png)

**Comment by bowenc0221** [comment]
I believe you should use `MODEL.WEIGHTS` instead of `TEST.MODEL_FILE`

**Comment by xukaiyan** [comment]
ok.thanks!

**Comment by anja-sheppard** [comment]
@bowenc0221 @xukaiyan I am having this same issue. I am running the following command:
`python3 tools/demo.py --cfg configs/panoptic_deeplab_R50_os32_cityscapes.yaml --input-files /home/abc/Downloads/cs.png --merge-image --output-dir out MODEL.WEIGHTS panoptic_deeplab_R50_os32_cityscapes.pth` on the image attached.

![cs](https://github.com/bowenc0221/panoptic-deeplab/assets/11894685/4b38694c-e704-4cf9-a296-56bafaef7706)

However the result looks like this:
![panoptic_pred_0](https://github.com/bowenc0221/panoptic-deeplab/assets/11894685/77c52e94-f4af-4ea0-9346-2027dae9025a)
