### ISSUE TITLE
About pretraining with Mapillary Vistas

### ISSUE THREAD

**Issue by pingjun18-li** [bowenc0221/panoptic-deeplab#93]
Hi,bowen, thanks for you codes again. And I have a question about pretrain on Mapillary Vistas.
It is general to pretrain with Mapillary Vistas and fine-tune on Cityscapes. The thing and stuff categories are quite different for these two data sets, is there some special treatment required?
Especially, some things (e.g. traffic lights, poles) in Mapillary Vistas are marked as stuff in Cityscapes, how you deal with such categories?

**Comment by bowenc0221** [comment]
There is no special treatment, we just throw the head (from MV), reinitialize it and finetune on Cityscapes.

**Comment by pingjun18-li** [comment]
OK, I've got it. Thank you for your prompt reply！
