### ISSUE TITLE
Problem about visulizing the predict result 

### ISSUE THREAD

**Issue by guoxuerui** [bowenc0221/panoptic-deeplab#94]
After training the model on custom dataset, we want to visualize the predict result with trained weight. However,  when use `v.draw_panoptic_seg_predictions` , the argument `segments_info` is not directly result from Panoptic-Deeplab prediction, the latter results contains three keys ['sem_seg', 'panoptic_seg', 'instances'], so we have no clue where the segements_info come from, is there any visulization tutorial we could follow?

**Comment by bowenc0221** [comment]
You can pass `panoptic_seg` and set `segments_info` to `None`.
