### ISSUE TITLE
About the Mean and Std of Mapillary_Vistas dataset?

### ISSUE THREAD

**Issue by pingjun18-li** [bowenc0221/panoptic-deeplab#96]
Sorry to bother you again. I want to do an experiment on MV(Mapillary Vistas) dataset, but I have found many projects without its description and haven't shared the codes about training on MV. Would you like to share the value of "mean" and "std" about MV?
Thank you so much!

**Comment by bowenc0221** [comment]
We use the ImageNet "mean" and "std".

I plan to release a new codebase that includes models from 5 semantic segmentation datasets (including Mapillary Vistas) and 2 panoptic segmentation datasets. I will let you know when it is online. Stay tuned!

**Comment by pingjun18-li** [comment]
ok, thank you so much for your great jobs! And looking forward to your new achievements!

**Comment by bowenc0221** [comment]
@pingjun18-li 

Please check my new codebase for semantic and panoptic segmentation: https://github.com/facebookresearch/MaskFormer

It supports (and have pre-trained weights) 5 major semantic segmentation datasets and 2 panoptic segmentation datsaets.

**Comment by pingjun18-li** [comment]
Wow, nice, I'll take it seriously and make full use of it!
