### ISSUE TITLE
How to visualize all panoptic segmentation results of validation dataset

### ISSUE THREAD

**Issue by MY-LIU100101** [bowenc0221/panoptic-deeplab#98]
Hi,

Could anyone please tell me, can I save the panoptic segmentation results of the validation dataset as images using existing codes?

**Comment by rajkumar-surana** [comment]
Hey, let us know if you find anything.
Inference in detectron2 is giving a predictions.json file, how one can use it for visualization on the test set?

**Comment by bowenc0221** [comment]
Predictions are saved in a temp folder which will be automatically deleted after the program finishes. You will need to write your own evaluator to save predictions.

Reference: https://github.com/facebookresearch/detectron2/blob/0fb7f0432aa4f9e50360402f59bace32356d7c58/detectron2/evaluation/panoptic_evaluation.py#L126

**Comment by rajkumar-surana** [comment]
Thank you for pointing it out, I will try to modify the code.

**Comment by ding-Chen** [comment]
@rajkumar-surana Hi,  do you know how to visualize all panoptic segmentation results of the validation dataset?
